name: one_ui
description: Flutter widgets implementing Samsung One UI. Based on the official documentation.
version: 0.3.2
homepage: https://github.com/tockiib/one_ui

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
